"""Problem definitions for the high-dimensional linear-composite class.

Each :class:`Problem` bundles the four pure functions the simulators need:

* ``grad(params, data, target)``      -> per-sample gradient, shape ``(D, M)``
* ``target(optimal_params, data)``    -> label(s) generated by the teacher
* ``f(q)``                            -> population "gradient profile" used by the
  B-functionals (``discounts.py``); ``q`` carries the logits in its last axis,
  laid out as ``[student (M) | teacher (M*)]``
* ``risk_from_B(B)``                  -> scalar risk from the low-dim statistic ``B``

These are the same maps that lived in the old ``risks_and_discounts.py``; they are
collected here behind a small registry so ``simulate``/``dynamics`` can close over a
single static object.
"""
from __future__ import annotations

from typing import Callable, NamedTuple

import jax
import jax.numpy as jnp
from jax import jit
from jax.nn import log_softmax, sigmoid, softmax
from numpy.polynomial.hermite import hermgauss


class Problem(NamedTuple):
    name: str
    grad: Callable        # (params, data, target) -> (D, M)
    target: Callable      # (optimal_params, data) -> target
    f: Callable           # (q) -> profile, q[..., :M]=student, q[..., M:]=teacher
    risk_from_B: Callable  # (B) -> scalar


# --------------------------------------------------------------------------- #
# Linear regression
# --------------------------------------------------------------------------- #
@jit
def _grad_linreg(params, data, target):
    return jnp.outer(data, data @ params - target)


@jit
def _target_linreg(optimal_params, data):
    return optimal_params.T @ data


@jit
def _f_linreg(q):
    m = q.shape[-1] // 2
    return q[..., :m] - q[..., m:]


@jit
def _risk_from_B_linreg(B):
    n = B.shape[0] // 2
    return (jnp.trace(B) - 2 * jnp.trace(B[:n, n:])) / 2


# --------------------------------------------------------------------------- #
# Logistic regression (binary)
# --------------------------------------------------------------------------- #
@jit
def _logreg_prob(data, params):
    return sigmoid(params.T @ data)


@jit
def _grad_logreg(params, data, target):
    return jnp.outer(data, _logreg_prob(data, params) - target)


@jit
def _target_logreg(optimal_params, data):
    return sigmoid(optimal_params.T @ data)


@jit
def _f_logreg(q):
    m = q.shape[-1] // 2
    return sigmoid(q[..., :m]) - sigmoid(q[..., m:])


@jit
def _risk_from_B_logreg(B):
    # Binary logistic regression only: B is 2x2.
    B00, B11, B01 = B[0, 0], B[1, 1], B[0, 1]
    num_points = 20
    points, weights = hermgauss(num_points)
    points = jnp.asarray(points) * jnp.sqrt(2.0)
    weights = jnp.asarray(weights)
    t1 = -B01 * jnp.exp(jnp.sqrt(B11) * points) / (1 + jnp.exp(jnp.sqrt(B11) * points)) ** 2
    t2 = jnp.log1p(jnp.exp(jnp.sqrt(B00) * points))
    return jnp.sum(weights * (t1 + t2)) / jnp.sqrt(jnp.pi)


# --------------------------------------------------------------------------- #
# Real phase retrieval
# --------------------------------------------------------------------------- #
@jit
def _grad_real_phase_ret(params, data, target):
    pd = params.T @ data
    return jnp.outer(data, 4 * pd * (pd ** 2 - target))


@jit
def _target_real_phase_ret(optimal_params, data):
    return (optimal_params.T @ data) ** 2


@jit
def _f_real_phase_ret(q):
    m = q.shape[-1] // 2
    q1, q2 = q[..., :m], q[..., m:]
    return 4 * q1 * (q1 ** 2 - q2 ** 2)


@jit
def _risk_from_B_real_phase_ret(B):
    m = B.shape[0] // 2
    B11, B12, B22 = B[:m, :m], B[:m, m:], B[m:, m:]
    return (3 * jnp.trace(B11 @ B11) - 2 * jnp.trace(B11 @ B22)
            - 4 * jnp.trace(B12 @ B12.T) + 3 * jnp.trace(B22 @ B22))


PROBLEMS = {
    "linreg": Problem("linreg", _grad_linreg, _target_linreg, _f_linreg, _risk_from_B_linreg),
    "logreg": Problem("logreg", _grad_logreg, _target_logreg, _f_logreg, _risk_from_B_logreg),
    "real_phase_ret": Problem(
        "real_phase_ret", _grad_real_phase_ret, _target_real_phase_ret,
        _f_real_phase_ret, _risk_from_B_real_phase_ret,
    ),
}


def make_softmax_problem(classes: int, *, risk_samples: int = 8_192,
                         risk_seed: int = 0) -> Problem:
    """Create a ``classes``-class soft-label teacher--student problem.

    The student and teacher use ``classes - 1`` free logits, with the last
    class fixed as the reference logit.  This removes softmax's additive gauge
    direction and keeps the Gaussian order parameter nonsingular.
    The population cross-entropy is evaluated from ``B`` with fixed Gaussian
    Monte Carlo draws, so repeated calls along an ODE path are deterministic.
    """
    if classes < 2:
        raise ValueError("classes must be at least two")
    rank = classes - 1
    base = jax.random.normal(
        jax.random.PRNGKey(risk_seed), (risk_samples, 2 * rank)
    )

    def probabilities(free_logits):
        reference = jnp.zeros(free_logits.shape[:-1] + (1,))
        return softmax(jnp.concatenate([free_logits, reference], axis=-1), axis=-1)

    @jit
    def grad(params, data, target):
        return jnp.outer(data, probabilities(params.T @ data)[:-1] - target[:-1])

    @jit
    def target(optimal_params, data):
        return probabilities(optimal_params.T @ data)

    @jit
    def f(q):
        return probabilities(q[..., :rank])[..., :-1] - probabilities(
            q[..., rank:]
        )[..., :-1]

    @jit
    def risk_from_B(B):
        symmetric = (B + B.T) / 2
        scale = jnp.maximum(jnp.trace(symmetric) / (2 * rank), 1.0)
        chol = jnp.linalg.cholesky(
            symmetric + 1e-10 * scale * jnp.eye(2 * rank)
        )
        q = base @ chol.T
        student_log_probability = log_softmax(
            jnp.concatenate([q[:, :rank], jnp.zeros((risk_samples, 1))], axis=1),
            axis=-1,
        )
        teacher_probability = probabilities(q[:, rank:])
        return -jnp.mean(
            jnp.sum(teacher_probability * student_log_probability, axis=-1)
        )

    return Problem(
        f"softmax_{classes}", grad, target, f, risk_from_B
    )


def get_problem(name: str) -> Problem:
    try:
        return PROBLEMS[name]
    except KeyError:
        raise NotImplementedError(f"Problem {name!r} not implemented") from None
